title: OrcaSlicer DEB Repository
email: robert843@o2.pl
description: >-
  This project provides a non-official DEB repository for the popular 3D printing slicer, OrcaSlicer. It offers a convenient way for users on Debian-based systems (like Debian, Ubuntu, and Linux Mint) to install and update OrcaSlicer directly via their system's package manager.

  By packaging the application as a DEB, this repository ensures proper system integration, including automatic updates and correct desktop environment shortcuts. This eliminates the need for manual handling of AppImage files, offering a seamless and native installation experience.
url: "https://robert843.github.io"
baseurl: "/OrcaSlicer-deb"
github_username: robert843

# Build settings
theme: minima
plugins:
  - jekyll-feed
exclude:
  - tools/
  - doc/